apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
  labels:
    name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabel:
      name: nginx 
  template:
    metadata:
      labels:
      name: nginx
  spec:
    containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
      
